name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clean build directory
      run: |
        rm -rf build
        mkdir build
    - name: Configure with CMake
      run: cmake -B build -S .
    - name: make
      run: make -C build
