name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake
    - name: make
      run: make -C build
    - name: make check
      run: make -C build check
    - name: make distcheck
      run: make -C build distcheck
